---
galaxy_info:
  author: Robert de Bock
  description: Install buildtools.
  license: Apache License, Version 2.0
  min_ansible_version: 2.2
  min_ansible_container_version: 0.2.0

  platforms:
    - name: Alpine
      versions:
        - all
    - name: Debian
      versions:
        - jessie
        - buster
    - name: EL
      versions:
        - 6
        - 7
    - name: Fedora
      versions:
        - 26
        - 27
    - name: Ubuntu
      versions:
        - artful
        - zesty

  galaxy_tags:
    - epel
    - repository
    - installer
    - packages
    - Alpine
    - CentOS
    - Fedora
    - Debian
    - Ubuntu
    - RHEL

dependencies:
  - robertdebock.ansible-role-bootstrap
