---
# tasks file for docker
- name: install software
  package: 
    name: docker
    state: present
  when:
    - ansible_product_version >= "2.0"

- name: start and enable docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: uninstall software (pip)
  pip:
    name: docker-py
    state: absent

- name: install software (pip)
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
  with_items:
    - name: docker
      version: 2.5.1
    - name: docker-compose
