---
# tasks file for docker
- name: install software
  package:
    name: docker
    state: present

- name: start and enable docker using service
  service:
    name: docker
    state: started
    enabled: yes

- name: uninstall software (pip)
  pip:
    name: docker-py
    state: absent

- name: install software (pip)
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
  with_items: "{{ packages }}"
