---
# tasks file for docker
- name: load default variables
  include_vars:
    file: default.yml

- name: load os-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - default.yml

- name: prepare debian with apt-transport-https
  package:
    name: apt-transport-https
  when:
    - ansible_distribution == "Debian"

- name: prepare debian with apt key
  apt_key:
    keyserver: pgp.mit.edu
    id: 58118E89F3A912897C070ADBF76221572C52609D
  when:
    - ansible_distribution == "Debian"
  register: result
  until: result is succeeded
  retries: 3

- name: prepare debian with repository
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo {{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }} main
  when:
    - ansible_distribution == "Debian"

- name: install software
  package:
    name: "{{ item }}"
  with_items: "{{ docker_packages }}"

- name: install modules
  pip:
    name: "{{ item.name }}"
    version: "{{ item.version | default(omit) }}"
  with_items: "{{ docker_pip_modules }}"

- name: start and enable docker
  service:
    name: "{{ docker_service }}"
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"
