---
# tasks file for docker
- name: include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "docker.{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "docker.{{ ansible_distribution }}.yml"
    - "docker.default.yml"

- name: prepare debian with apt-transport-https
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
  when:
    - ansible_distribution == "Debian"

- name: prepare debian with apt key
  apt_key:
    keyserver: pgp.mit.edu
    id: 58118E89F3A912897C070ADBF76221572C52609D
  when:
    - ansible_distribution == "Debian"

- name: prepare debian with repository
  apt_repository:
    repo: deb https://apt.dockerproject.org/repo {{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }} main
    state: present
  when:
    - ansible_distribution == "Debian"

- name: install software
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ docker_packages }}"

- name: install modules
  pip:
    name: "{{ item }}"
  with_items:
    - "{{ docker_modules }}"

- name: start and enable docker
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ docker_services }}"
  when:
    - ansible_virtualization_type != "docker"
