---
# tasks file for ansible-role-epel
- name: install epel-release
  package:
    name: epel-release
    state: present
  when:
    - ( ansible_distribution == "CentOS" or ansible_distribution == "Red Hat Enterprise Linux" )
