---
- name: robertdebock.ansible-role-epel
  src: robertdebock.ansible-role-epel
- name: robertdebock.ansible-role-scl
  src: robertdebock.ansible-role-scl
- name: robertdebock.ansible-role-buildtools
  src: robertdebock.ansible-role-buildtools
