---
- name: Converge
  hosts: all

  roles:
    - role: ansible-role-docker

  tasks:
  - name: Create a container
    docker_container:
      name: openssh
      image: robertdebock/docker-centos-openssh
      ports:
      - "2222:22"
