---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Create a container
      docker_container:
        name: openssh
        image: robertdebock/docker-centos-openssh
        ports:
          - "2222:22"
      when:
        - ansible_connection != "docker"
