---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: create a container
      docker_container:
        name: openssh
        image: robertdebock/docker-centos-openssh
        ports:
          - "2222:22"
      when:
        - ansible_connection not in [ "container", "docker", "community.docker.docker" ]

    - name: make sure we are not running podman
      ansible.builtin.command:
        cmd: docker --version
      register: docker_test_one
      failed_when:
        - '"podman" in docker_test_one.stdout'
