---
# tasks file for ansible-role-python-pip
- name: include distribution specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "default.yml"

- name: install software
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: add python27 to ldconfig
  copy:
    src: files/python27.conf
    dest: /etc/ld.so.conf.d/python27.conf
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"
  notify: run ldconfig

- name: run handlers
  meta: flush_handlers

- name: link pip
  file:
    src: /opt/rh/python27/root/usr/bin/pip
    dest: /usr/bin/pip
    state: link
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"

- name: update pip
  pip:
    name: pip
    state: present
    version: "{{ version }}"
    executable: "{{ executable | default(omit) }}"
